import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <body className="min-h-screen w-full flex flex-col [--pattern-fg:var(--color-neutral-900)]/5 dark:[--pattern-fg:var(--color-neutral-50)]/5">
          <main className="bg-background text-foreground">{children}</main>
        </body>
      </ThemeProvider>
    </html>
  );
}
